/**
 * fetch-fonts.mjs — vendors the Google Fonts webfonts into client/public/fonts/.
 *
 * index.html used to pull Plus Jakarta Sans and JetBrains Mono straight from
 * fonts.googleapis.com. That is an outbound request to a third party on every page load,
 * which the static demo build must not make — and which the app has no need to make either.
 *
 * Run once; the downloaded .woff2 files and the generated fonts.css are committed. Re-run only
 * to change weights or refresh the files.
 *
 *   node scripts/fetch-fonts.mjs
 */

import { mkdirSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
// Deliberately under src/, not public/: files in public/ are copied verbatim, so their URLs
// would stay absolute and 404 on a GitHub Pages project site served from a subdirectory.
// Under src/ the stylesheet is processed by Vite, which hashes the files and rewrites the
// URLs against whatever base the build uses.
const FONT_DIR = join(REPO_ROOT, 'client', 'src', 'fonts')

// Exactly the families/weights index.html requested.
const GOOGLE_CSS_URL =
  'https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&family=JetBrains+Mono:wght@500;700;800&display=swap'

// A modern browser UA makes Google serve woff2 (with an old UA it falls back to ttf).
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'

const css = await fetch(GOOGLE_CSS_URL, { headers: { 'User-Agent': UA } }).then((r) => {
  if (!r.ok) throw new Error(`Google Fonts CSS: HTTP ${r.status}`)
  return r.text()
})

mkdirSync(FONT_DIR, { recursive: true })

const urls = [...new Set(css.match(/https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2/g) ?? [])]
if (urls.length === 0) throw new Error('No woff2 URLs found in the Google Fonts CSS')

console.log(`[fonts] ${urls.length} woff2 files referenced`)

let localCss = css
let bytes = 0
for (const url of urls) {
  // e.g. .../plusjakartasans/v8/abc123.woff2 → plusjakartasans-abc123.woff2
  const parts = url.split('/')
  const family = parts[parts.length - 3]
  const name = `${family}-${parts[parts.length - 1]}`
  const buf = Buffer.from(await fetch(url, { headers: { 'User-Agent': UA } }).then((r) => r.arrayBuffer()))
  writeFileSync(join(FONT_DIR, name), buf)
  bytes += buf.length
  // Relative to this stylesheet, so the reference survives any base path.
  localCss = localCss.replaceAll(url, `./${name}`)
  console.log(`  ${name}  ${(buf.length / 1024).toFixed(1)} KB`)
}

writeFileSync(
  join(FONT_DIR, 'fonts.css'),
  `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.\n` +
    `   Vendored from Google Fonts so the app makes no third-party requests.\n` +
    `   Source: ${GOOGLE_CSS_URL} */\n\n${localCss}`,
  'utf8',
)

console.log(`[fonts] total ${(bytes / 1024).toFixed(1)} KB → client/src/fonts/`)
